//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMember
    {
        public int Id { get; set; }
        public int CommitteeSeatId { get; set; }
        public int FacultyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> ElectionId { get; set; }
        public bool Appointed { get; set; }
        public string Notes { get; set; }
    
        public virtual CommitteeSeat CommitteeSeat { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
