//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeSeat
    {
        public CommitteeSeat()
        {
            this.CommitteeMember = new HashSet<CommitteeMember>();
            this.ElectionNomination = new HashSet<ElectionNomination>();
            this.ElectionSpecialSeat = new HashSet<ElectionSpecialSeat>();
        }
    
        public int Id { get; set; }
        public int CommitteeId { get; set; }
        public Nullable<int> FacultySchoolId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> StaggerYear { get; set; }
    
        public virtual Committee Committee { get; set; }
        public virtual ICollection<CommitteeMember> CommitteeMember { get; set; }
        public virtual FacultySchool FacultySchool { get; set; }
        public virtual ICollection<ElectionNomination> ElectionNomination { get; set; }
        public virtual ICollection<ElectionSpecialSeat> ElectionSpecialSeat { get; set; }
    }
}
