//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Election
    {
        public Election()
        {
            this.ElectionNomination = new HashSet<ElectionNomination>();
            this.ElectionSpecialSeat = new HashSet<ElectionSpecialSeat>();
            this.ElectionVote = new HashSet<ElectionVote>();
        }
    
        public int Id { get; set; }
        public int ElectionTypeId { get; set; }
        public System.DateTime NominationStartDate { get; set; }
        public System.DateTime NominationEndDate { get; set; }
        public System.DateTime VotingStartDate { get; set; }
        public System.DateTime VotingEndDate { get; set; }
        public System.DateTime TermStartDate { get; set; }
    
        public virtual ElectionType ElectionType { get; set; }
        public virtual ICollection<ElectionNomination> ElectionNomination { get; set; }
        public virtual ICollection<ElectionSpecialSeat> ElectionSpecialSeat { get; set; }
        public virtual ICollection<ElectionVote> ElectionVote { get; set; }
    }
}
