//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyDiscipline
    {
        public FacultyDiscipline()
        {
            this.Faculty = new HashSet<Faculty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int FacultySchoolId { get; set; }
    
        public virtual ICollection<Faculty> Faculty { get; set; }
        public virtual FacultySchool FacultySchool { get; set; }
    }
}
