//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.CommitteeMember = new HashSet<CommitteeMember>();
            this.ElectionNomination = new HashSet<ElectionNomination>();
            this.ElectionVote_Nominee = new HashSet<ElectionVote>();
            this.ElectionVote_Voter = new HashSet<ElectionVote>();
        }
    
        public int Id { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Email { get; set; }
        public Nullable<int> FacultyDisciplineId { get; set; }
        public Nullable<int> FacultyRankId { get; set; }
        public bool Tenure { get; set; }
        public bool Graduate { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CommitteeMember> CommitteeMember { get; set; }
        public virtual ICollection<ElectionNomination> ElectionNomination { get; set; }
        public virtual ICollection<ElectionVote> ElectionVote_Nominee { get; set; }
        public virtual ICollection<ElectionVote> ElectionVote_Voter { get; set; }
        public virtual FacultyDiscipline FacultyDiscipline { get; set; }
        public virtual FacultyRank FacultyRank { get; set; }
    }
}
