//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacultySenateDBEntities : DbContext
    {
        public FacultySenateDBEntities()
            : base("name=FacultySenateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Committee> Committees { get; set; }
        public DbSet<CommitteeMember> CommitteeMembers { get; set; }
        public DbSet<CommitteeSeat> CommitteeSeats { get; set; }
        public DbSet<CommitteeType> CommitteeTypes { get; set; }
        public DbSet<Election> Elections { get; set; }
        public DbSet<ElectionNomination> ElectionNominations { get; set; }
        public DbSet<ElectionSpecialSeat> ElectionSpecialSeats { get; set; }
        public DbSet<ElectionType> ElectionTypes { get; set; }
        public DbSet<ElectionVote> ElectionVotes { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<FacultyDiscipline> FacultyDisciplines { get; set; }
        public DbSet<FacultyRank> FacultyRanks { get; set; }
        public DbSet<FacultySchool> FacultySchools { get; set; }
    }
}
