//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultySenateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultySchool
    {
        public FacultySchool()
        {
            this.CommitteeSeat = new HashSet<CommitteeSeat>();
            this.FacultyDiscipline = new HashSet<FacultyDiscipline>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual ICollection<CommitteeSeat> CommitteeSeat { get; set; }
        public virtual ICollection<FacultyDiscipline> FacultyDiscipline { get; set; }
    }
}
